<?php

declare(strict_types=1);

use Drupal\Core\Render\Element;

/**
 * Implements hook_page_attachments().
 *
 * Unconditionally attaches the 'refreshless/refreshless' library as there is a
 * noticeable performance benefit to not having to initialize the whole DOM and
 * page even with the page cache active.
 *
 * @see \refreshless_page_attachments()
 *   Conditionally attaches the 'refreshless/refreshless' library only when a
 *   session is active.
 */
function omnipedia_refreshless_page_attachments(array &$page): void {
  $page['#attached']['library'][] = 'refreshless/refreshless';
}

/**
 * Implements \hook_preprocess_HOOK() for region templates.
 *
 * This adds the 'hidden' attribute to regions that contain only the
 * RefreshLess placeholder element to avoid layout issues resulting from this
 * module forcing all regions to render.
 *
 * @todo Remove when @link
 *   https://www.drupal.org/project/refreshless/issues/3293592 issue 3293592
 *   @endLink is merged.
 */
function omnipedia_refreshless_preprocess_region(array &$variables): void {

  /** @var string[] All child element keys minus the RefreshLess placeholder. */
  $childKeys = \array_diff(
    Element::children($variables['elements']),
    ['refreshless_trigger_region_wrapper_markup']
  );

  /** @var string[] All child element keys that have rendered markup. */
  $childKeysWithMarkup = \array_filter(
    $childKeys, function($name) use ($variables) {
      // Only include elements that actually contain markup. Blocks that
      // implement lazy builder callbacks - such as the help block - will still
      // result in an entry here but will have a '#markup' containing an empty
      // string if the lazy builder did not output anything for this
      // invocation.
      return !empty($variables['elements'][$name]['#markup']);
    }
  );

  // Add the 'hidden' attribute to this region if the only rendered element is
  // the RefreshLess placeholder.
  if (count($childKeysWithMarkup) === 0) {
    $variables['attributes']['hidden'] = true;
  }

}
