<?php

declare(strict_types=1);

/**
 * Implements hook_page_attachments().
 *
 * Unconditionally attaches the 'refreshless/refreshless' library as there is a
 * noticeable performance benefit to not having to initialize the whole DOM and
 * page even with the page cache active.
 *
 * @see \refreshless_page_attachments()
 *   Conditionally attaches the 'refreshless/refreshless' library only when a
 *   session is active.
 */
function omnipedia_refreshless_page_attachments(array &$page): void {
  $page['#attached']['library'][] = 'refreshless/refreshless';
}
